### ISSUE TITLE
Parallel connection error

### ISSUE THREAD

**Issue by bimusiek** [timotheus/ebaysdk-python#102]
I run on one problem and before digging into code I would like to ask if I am doing everything correctly. 

I am running Parallel more or less like in docs, I have one property `parallel = Parallel()` that I pass as kwarg to instances of Trading Connection, then I am doing execute() (one per one instance of Connection()) and later `parallel.wait()`. I check for `p.error()` also if not, I return responses.

Problem that I am facing is coming from gevent, it raises ConnectionError (timed out)
	
	Traceback (most recent call last):
	  File "/opt/inventorum/ebay/eggs/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
	    result = self._run(*self.args, **self.kwargs)
	  File "/opt/inventorum/ebay/eggs/grequests-0.2.0-py2.7.egg/grequests.py", line 71, in send
	    self.url, **merged_kwargs)
	  File "/opt/inventorum/ebay/eggs/requests-2.6.0-py2.7.egg/requests/sessions.py", line 464, in request
	    resp = self.send(prep, **send_kwargs)
	  File "/opt/inventorum/ebay/eggs/requests-2.6.0-py2.7.egg/requests/sessions.py", line 613, in send
	    r.content
	  File "/opt/inventorum/ebay/eggs/requests-2.6.0-py2.7.egg/requests/models.py", line 733, in content
	    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
	  File "/opt/inventorum/ebay/eggs/requests-2.6.0-py2.7.egg/requests/models.py", line 663, in generate
	    raise ConnectionError(e)
	ConnectionError: HTTPSConnectionPool(host='api.ebay.com', port=443): Read timed out.
	<Greenlet at 0x289bfa50: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x264dd5d0>>(stream=False)> failed with ConnectionError

And then I got AttributeError because there were no response and yet ebay sdk still tried to parse it:

	    self.parallel.wait(self.timeout)
	  File "/opt/inventorum/ebay/eggs/ebaysdk-2.1.0.dev1-py2.7.egg/ebaysdk/parallel.py", line 70, in wait
	    r.process_response()
	  File "/opt/inventorum/ebay/eggs/ebaysdk-2.1.0.dev1-py2.7.egg/ebaysdk/connection.py", line 184, in process_response
	    parse_response=parse_response)
	  File "/opt/inventorum/ebay/eggs/ebaysdk-2.1.0.dev1-py2.7.egg/ebaysdk/response.py", line 134, in __init__
	    self._dom = self._parse_xml(obj.content)
	AttributeError: 'NoneType' object has no attribute 'content'
	
Any ideas why it failed? I checked and in parallel.py there is try:except to catch `ConnectionError`.

**Comment by bimusiek** [comment]
I see that `grequest` accepts `exception_handler=` to handle exceptions. I guess this is an issue, I will prepare PR :+1:

**Comment by bimusiek** [comment]
I see it is more complicated than this, I had to use fork of grequests with all fixes and exception handlers cause owner on original grequests I think abandoned project.
So I added `exception_handler` and used `https://github.com/rtdean/grequests/tree/0.3.0`. I am not sure if I should make MR now.

**Comment by timotheus** [comment]
Considering the lack of support from grequests and some prior feedback, I'm considering moving to an approach that just calls gevent. The below works as is with gevent. I'm still looking it, but wanted to throw this out in hopes to get feedback.        

```        
        import gevent
        from ebaysdk.finding import Connection as finding

        api1 = finding(debug=opts.debug, appid=opts.appid, config_file=opts.yaml)
        api2 = finding(debug=opts.debug, appid=opts.appid, config_file=opts.yaml)
        api3 = finding(debug=opts.debug, appid=opts.appid, config_file=opts.yaml)
        api4 = finding(debug=opts.debug, appid=opts.appid, config_file=opts.yaml)

        calls = [
            gevent.spawn(api1.execute, 'findItemsAdvanced', {'keywords': 'python'}),
            gevent.spawn(api2.execute, 'findItemsAdvanced', {'keywords': 'perl'}),
            gevent.spawn(api3.execute, 'findItemsAdvanced', {'keywords': 'java'}),
            gevent.spawn(api4.execute, 'findItemsAdvanced', {'keywords': 'ruby'}),
        ]

        gevent.joinall(calls)

        for c in calls:
            print len(c.value.dict())
```

**Comment by timotheus** [comment]
After looking into this more I feel gevent is the best approach for making parallel calls. So much, that I'll likely deprecate the builtin parallel.py class unless I hear otherwise from users. I've committed an example that shows how to do this and capture any exceptions.

https://github.com/timotheus/ebaysdk-python/blob/master/samples/parallel_gevent.py

**Comment by bimusiek** [comment]
I think it is good idea, I have used grequest 3.0 for some time with fork but to be honest, ebay does not behave well with 10 request at a time. At the end we switched to normal synchronous requests. 

I would vote for your own gevent implementation in ebay. +1
