### ISSUE TITLE
UploadSiteHostedPicture with base64 picture

### ISSUE THREAD

**Issue by fwi-odoo** [timotheus/ebaysdk-python#104]
Hello,

I'm trying to upload my local pictures on eBay in order to use them when listing items. In the documentation, it is written that it's feasible by putting the parameter 'PictureData' in the request which is a reference to the binary attachment.
My question is how can I define the CallData in my call in order to have the binary attachment:
api.execute('UploadSiteHostedPicture', CallData)

Thanks,
Regards,

**Comment by timotheus** [comment]
The SDK doesn't have support for a binary upload yet. That said, one could add support for it. It's a matter of base64 encoding the image and doing to multi-part processing. Here's a prior thread about this.

https://github.com/timotheus/ebaysdk-python/issues/54

-Tim

**Comment by rowbare** [comment]
Tim,

I have a working solution to allow submitting files from the file system on my fork. I will add an example and submit a pull request for your consideration.

bob

**Comment by fwi-odoo** [comment]
Hello Tim,

Any idea when you will have time to look into the pull request of rowbare? 

Thanks for your time anyway great library,
Regards.

**Comment by carltaylor43** [comment]
yeah direct upload of base64 would be great, eBay server seems to be very fussy about what URL it will pull an image from (though it could be I'm doing something wrong obviously)

yeah great lib... I made my own in Obj-C but this is so much more of a time saver when keeping up with eBay API changes.

**Comment by timotheus** [comment]
I will be able to look into this by this Friday. I did an initial look and noticed it wasn't using multi-part upload which could introduce memory bloat when upload larger images. I'll dig into it again and report back soon.

**Comment by rowbare** [comment]
Tim,

Check out build_request in connection.py of my PR. Clearing the content-type header coerces Request to set the appropriate content-type: multipart/form-data.

Hope that will help your due diligence.

BTW here is a nice sugar pattern with Pillow installed (minus error checking):

from PIL import Image
with Image.open('c:/temp/testimage/123.jpg') as im:
        # scale the image to a suitable size
        # use thumbnail to scale to the bounding box
        # use resize if you want to calculate the dims 
	im.thumbnail((1600,1600))
	with io.BytesIO() as fp:
		im.save(fp, "JPEG")

		files = {'file': ('EbayImage', fp.getvalue())}
		pictureData = {
			"WarningLevel": "High",
			"PictureSet":'Supersize',
			"PictureName": "WorldLeaders"
		}
		response = api.execute('UploadSiteHostedPictures', pictureData, files=files)
		print(response.reply.SiteHostedPictureDetails.FullURL)


bob

**Comment by timotheus** [comment]
FYI, I just merged rowbare's PR.
