### ISSUE TITLE
AddItem with HTML description

### ISSUE THREAD

**Issue by fwi-odoo** [timotheus/ebaysdk-python#110]
Hello,

I'm currently trying to list an item with an HTML description. The eBay documentation says: 
you can submit your description using CDATA if you want to use HTML or XML-reserved characters in the description.

So I was wondering how I can mention to the API that I want to use CDATA for my description? 

Thanks

**Comment by timotheus** [comment]
Hi,

Within the Description element you can include CDATA like so,

```python
"Description": "<![CDATA[Since this is a CDATA section I can use all sorts of reserved characters like \" and & or write things like <foo></bar>but my document is still well formed! ]]>",
```

Which should result in the following,

```xml
<Description>
<![CDATA[Since this is a CDATA section I can use all sorts of reserved characters like " and & or write things like <foo></bar>but my document is still well formed! ]]>
</Description>
```

**Comment by fwi-odoo** [comment]
Hi,

Thank you for the answer. Works perfectly.
