### ISSUE TITLE
Trading API pageination setting fail to retrieve 2nd page

### ISSUE THREAD

**Issue by mrkmchau** [timotheus/ebaysdk-python#114]
Hi mate,
Thank you for your great ebay tools!
Currently I am working on trading API, I want to retrieve all my active listings in production environment.
I got 200 entries but as the setting in (Try 1) and (Try 2) below I set the ActiveList Pagination EntriesPerPage to 100 only.
It seems the "ActiveList.Pagination.EntriesPerPage":100 doesn't work.
and then I try to made another call the retrieve the 2nd page.
The result is same as first call. It seems the API can only retrieve the 1st page with 200 entries.

I am also try to quote the number to avoid error but the result is the same.

Am I miss something? or Is there a bug on the python API in pagination?

The result from first call ( I modify the dict to print out like below)
======================================
PaginationResult->TotalNumberOfPages->2
PaginationResult->TotalNumberOfEntries->360
ItemArray->Item->ItemID->2008xxxxxxxxxxx
ItemArray->Item->SKU->ABC123456
ItemArray->Item->ListingType->FixedPriceItem
....
======================================

Try 1:
1st call code
=======================================
response1 = api.execute('GetMyeBaySelling', {"DetailLevel":"ReturnAll","ActiveList.Include":"true","ActiveList.Pagination.EntriesPerPage":100,"ActiveList.Pagination.PageNumber":1})
alist1=response1.dict()['ActiveList']
itemarray1=alist1['ItemArray']
items1=itemarray1['Item']

2nd call code
======================================
response2 = api.execute('GetMyeBaySelling', {"DetailLevel":"ReturnAll","ActiveList.Include":"true","ActiveList.Pagination.EntriesPerPage":100,"ActiveList.Pagination.PageNumber":2})
alist2=response2.dict()['ActiveList']
itemarray2=alist2['ItemArray']
items2=itemarray2['Item']

Try 2:
1st call code
=======================================
response1 = api.execute('GetMyeBaySelling', {"DetailLevel":"ReturnAll","ActiveList.Include":"true","ActiveList.Pagination.EntriesPerPage":"100","ActiveList.Pagination.PageNumber":"1"})
alist1=response1.dict()['ActiveList']
itemarray1=alist1['ItemArray']
items1=itemarray1['Item']

2nd call code
======================================
response2 = api.execute('GetMyeBaySelling', {"DetailLevel":"ReturnAll","ActiveList.Include":"true","ActiveList.Pagination.EntriesPerPage":100,"ActiveList.Pagination.PageNumber":"2"})
alist2=response2.dict()['ActiveList']
itemarray2=alist2['ItemArray']
items2=itemarray2['Item']

**Comment by timotheus** [comment]
The request data is incorrect. Please see the following in the samples directory. Instead of using dot notation in your keys it needs to be a dictionary data structure.

https://github.com/timotheus/ebaysdk-python/blob/master/samples/trading.py#L264

For example,

```
{
    "DetailLevel": "ReturnAll",
    "ActiveList": { 
        "Include": "true",
        "Pagination": {
            "EntriesPerPage":100,
            "PageNumber":"2"
        }
    }
}
```

**Comment by timotheus** [comment]
closing .. I hope this resolved your issue.
