### ISSUE TITLE
How to detect if attribute is one element or list of elements?

### ISSUE THREAD

**Issue by mw44118** [timotheus/ebaysdk-python#124]
I'm using GetCategoryFeatures to look up conditions allowed for an ebay category.  One category allows exactly one condition:

    In [22]: _8.reply.Category.ConditionValues.Condition
    Out[22]: {'DisplayName': 'New', 'ID': '1000'}

Meanwhile, another category comes back with a list of allowed conditons:

    In [23]: _14.reply.Category.ConditionValues.Condition
    Out[23]: 
    [{'DisplayName': 'New', 'ID': '1000'},
     {'DisplayName': 'New other (see details)', 'ID': '1500'},
     {'DisplayName': 'Used', 'ID': '3000'},
     {'DisplayName': 'For parts or not working', 'ID': '7000'}]

I know I could do something like

    if isinstance(ebay_response.reply.Category.ConditionValues.Condition, list):
        # iterate through list

    else:
        # process a single element

but I hate stuff like this.

Any ideas on a more elegant solution?

Thanks for writing this library by the way.  Is saving me a ton of time!

**Comment by timotheus** [comment]
absolutely agree. A while ago I added code in the SDK to force the proper datatype on list and date nodes.

https://github.com/timotheus/ebaysdk-python/blob/master/ebaysdk/trading/__init__.py#L268

Unfortunately the node for Category.ConditionValues.Condition was defined incorrectly.

I'll add a fix for that.
