### ISSUE TITLE
#text shows up when value is false-ish

### ISSUE THREAD

**Issue by mw44118** [timotheus/ebaysdk-python#127]
First off, this is a great package.  Thanks for writing it.

Second, when I use "#text" and "@attrs", and I point the text at something that evaluates to False, the XML rendered looks different!

    >>> ebaysdk.utils.dict2xml({'Item': {'WeightMajor': {'#text': 0, '@attrs': {'unit': 'oz'}}}})
    '<Item><WeightMajor unit="oz"><#text>0</#text></WeightMajor></Item>'

    >>> ebaysdk.utils.dict2xml({'Item': {'WeightMajor': {'#text': 1, '@attrs': {'unit': 'oz'}}}})
    '<Item><WeightMajor unit="oz">1</WeightMajor></Item>'

I suspect it is because of this section in dict2xml:

            if isinstance(root[key], dict):
                attrs, value = attribute_check(root[key])

                if not value:
                    value = dict2xml(root[key])

That `if not value` should probably something more specific.

**Comment by timotheus** [comment]
Ouch, good catch!  I'll fix that asap.
