### ISSUE TITLE
HTTPConnectionPool error on find_items_by_ids

### ISSUE THREAD

**Issue by kennychung** [timotheus/ebaysdk-python#128]
ConnectionError: HTTPConnectionPool(host='apifindingcore.vip.ebay.com', port=80): Max retries exceeded with url: /services/search/FindItemServiceNextGen/v1 (Caused by ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known')))

I am trying to pull more details of item by looking up item ID, I followed the sample code.
//response = api.find_items_by_ids('171979292650') for single item.

Am I doing this right? Thanks.

**Comment by kennychung** [comment]
I ended up using "response = api.execute('GetSingleItem', {'ItemID': '171979292650'})"

Thank you and closing the issue..

**Comment by texano00** [comment]
@kennychung 
Why, doing `response = api.execute('GetSingleItem', {'ItemID': '171979292650'})` i receive this response
`{'errorMessage': {'error': {'category': 'Request', 'domain': 'CoreRuntime', 'severity': 'Error', 'message': 'Service operation GetSingleItem is unknown', 'subdomain': 'Inbound_Meta_Data', 'parameter': {'value': 'GetSingleItem', '_name': 'Param1'}, 'errorId': '2000'}}`
?

Thanks

**Comment by texano00** [comment]
Sorry i was making an error while initializing the "api" object; `api = finding()` instead of `api = Shopping()`
