### ISSUE TITLE
finding api, outputSelector

### ISSUE THREAD

**Issue by stushurik** [timotheus/ebaysdk-python#142]
I am trying to get as much item details as possible. It seems that I should include all outputSelectors.
https://developer.ebay.com/devzone/finding/CallRef/findItemsAdvanced.html#Request.outputSelector

I tried to pass otuputSelector alongside keywords (tried to pass list of string). But I have got the same results each time (the same keys).

**Comment by matecsaj** [comment]
Perhaps this example with multiple output selectors will help. 

        request = {
            'categoryId': ['4196', '12595'],
            'itemFilter': [
                {'name': 'AvailableTo', 'value': 'CA'},
                {'name': 'ListingType', 'value': 'All'},
                {'name': 'PaymentMethod', 'value': 'PayPal'},
            ],
            'outputSelector': ['CategoryHistogram', 'GalleryInfo', 'PictureURLSuperSize', 'UnitPriceInfo'],
            'paginationInput': {
                'entriesPerPage': 10,
                'pageNumber': 1  # TODO iterate over pages
            },
            'sortOrder': 'EndTimeSoonest',
        }
