### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by kareemw9** [timotheus/ebaysdk-python#143]
Hi,

I've successfully ran a find api call. I've included my code below. However, even with pagination filters, I consistently only get the first page of possible 25,000+ results. Has anyone run into this issue before, and if so how was it resolved?

from ebaysdk.finding import Connection as Finding
import json

try:
    api = Finding(appid="APPID NUMBER", config_file=None)
    response = api.execute('findItemsAdvanced', {'keywords': 'Yeezy'},{'paginationInput.pageNumber':2})
    
    print(response.dict())
    
except ConnectionError as e:
    print(e)
    print(e.response.dict())

**Comment by piotr-szpetkowski** [comment]
Shouldn't arguments be in one dictionary?
Like:
```
params = {
    'keywords': 'Yeezy',
    'paginationInput': {
        'pageNumber': 2,
    }
}
response = api.execute('findItemsAdvanced', **params)
```

**Comment by timotheus** [comment]
The second arg to execute should be a dictionary.

`response = api.execute('findItemsAdvanced',  params)`

**Comment by piotr-szpetkowski** [comment]
True, my mistake. I've been a bit mindless at night and didn't really test it. I've edited my comment.
