### ISSUE TITLE
findItemsByProduct requires attribute type

### ISSUE THREAD

**Issue by jayfk** [timotheus/ebaysdk-python#15]
A `findItemsByProduct`call requires a `productId` with a `type` attribute set.

The resulting XML should look like this: 
`<ProductID type="ProductIDCodeType"> ProductIDType (string) </ProductID>`
eg:
 `<ProductID type="EAN"> 5702014734999 </ProductID>`

I couldn't find a way to produce XML like this using your SDK. Is this even possible?

**Comment by simplehumble** [comment]
`
    response = api.execute('findItemsByProduct', { 'productId type="ReferenceID"': '5002927655' })
    `

is this the right format for finding?

**Comment by timotheus** [comment]
It gets a little tricky when building the dict for a product request. Sometimes it's useful to test it directly using the dict2xml function.

```
product = {
  'productId': {
    '#text': '53039031', 
    '@attrs': {'type': 'ReferenceID'}
   }
}

from ebaysdk.utils import dict2xml
dict2xml(product)
```
```
Out[3]: '<productId type="ReferenceID">53039031</productId>'
```

So this is likely what you need
```
response = api.execute('findItemsByProduct', product)

**Comment by simplehumble** [comment]
> 53039031

thank you!!!
