### ISSUE TITLE
Incompatible with requests 2.11+

### ISSUE THREAD

**Issue by listingmirror** [timotheus/ebaysdk-python#162]
You guys are being too loosey goosy with your header types...  If a project upgrades to requests 2.11 or higher, it will blow up on making an API call.

See reproduction and stacktrace: https://github.com/kennethreitz/requests/issues/3512

Details on requests change here: https://github.com/kennethreitz/requests/issues/3477

I will make a pull request to fix this, if it will get merged?  I can't tell how active this project is anymore...

**Comment by listingmirror** [comment]
Here is a patch that "fixes" it... siteid needs to default to '0' not 0.  Int as a header is invalid.

https://github.com/listingmirror/ebaysdk-python/commit/09ec9f1335964e1e660e159b020cb17c4a65fa44

**Comment by timotheus** [comment]
A pull request would appreciated. Thanks!

**Comment by listingmirror** [comment]
OK pull request is merged thanks!

Any chance we can get a release too?

**Comment by timotheus** [comment]
Just released to Pypi. Thanks for the contribution!
