### ISSUE TITLE
GeteBayDetails DetailName=ShippingServiceDetails

### ISSUE THREAD

**Issue by mingworld** [timotheus/ebaysdk-python#165]
GeteBayDetails DetailName=ShippingServiceDetails

returns 

Code: 17460, Unknown Error. Unknown Error.

Not sure if this is eBay issue or sdk issue. 

Can anyone help?

**Comment by ncharlot** [comment]
Same error using API Test Tool so it's an eBay issue...

**Comment by mingworld** [comment]
Thank you @ncharlot
