### ISSUE TITLE
Uploading multi-variation listing using AddFixedPriceItem only uploads one variation

### ISSUE THREAD

**Issue by itayplavin** [timotheus/ebaysdk-python#168]
Specified like this in the item dictionary:

'Variations': {
                        'VariationSpecificsSet': {
                            'NameValueList': {
                                'Name': 'Size',
                                'Value':'10inches',
                                'Value':'12inches',
                                'Value':'14inches',
                                'Value':'16inches',
                            }
                        },
                        'Variation': {
                            'SKU':'10in',
                            'StartPrice':'10',
                            'Quantity':'1',
                            'VariationSpecifics':
                                {
                                'NameValueList': {
                                    'Name': 'Size',
                                    'Value': '10inches',
                                }
                            }
                        },
                        'Variation': {
                            'SKU':'12in',
                            'StartPrice':'12',
                            'Quantity':'1',
                            'VariationSpecifics':
                                {
                                'NameValueList': {
                                    'Name': 'Size',
                                    'Value': '12inches',
                                }
                            }
                        },
                        'Variation': {
                            'SKU':'14in',
                            'StartPrice':'14',
                            'Quantity':'1',
                            'VariationSpecifics':
                                {
                                'NameValueList': {
                                    'Name': 'Size',
                                    'Value': '14inches',
                                }
                            }
                        },
                        'Variation': {
                            'SKU':'16in',
                            'StartPrice':'24.99',
                            'Quantity':'1',
                            'VariationSpecifics':
                                {
                                'NameValueList': {
                                    'Name': 'Size',
                                    'Value': '16inches',
                                }
                            }
                        },`
Only the last ordered element (the 16 inches one) will actually be uploaded to ebay. The rest will be ignored. Definitely not an ebay server side issue as the AddFixedPriceItemRequest body only has a single variation child in it (the 16 inches one). It's probably something to do with how the dictionary is converted to XML.

**Comment by itayplavin** [comment]
Solution is similar to this:

https://github.com/timotheus/ebaysdk-python/issues/160

**Comment by timotheus** [comment]
There's a little bit of documentation around this as well,

https://github.com/timotheus/ebaysdk-python/wiki/Request-Dictionary#3-repeating-tags
