### ISSUE TITLE
Item.ItemCompatibilityList Input

### ISSUE THREAD

**Issue by darecAdirondack** [timotheus/ebaysdk-python#191]
Im using the eBay API and the python ebaysdk module. in my AddFixedPriceItem request to post a new item listing, i want to use Item.ItemCompatibility (In the ebayMotors Category using my Production Keys) but for some reason its just not working. 

According to the online documentation, this is the required xml input:

     `<ItemCompatibilityList> ItemCompatibilityListType
      <Compatibility> ItemCompatibilityType
        <CompatibilityNotes> string </CompatibilityNotes>
        <NameValueList> NameValueListType
          <Name> string </Name>
          <Value> string </Value>
          
        </NameValueList>
        
      </Compatibility>
      
    </ItemCompatibilityList>`

i have probably 15 or 20 different ways i could think of to rearrange my input to give ebay what they want, but none of them seemed to work. this is the most current bit of code i used in request:

       `api_request = {
            'Item': {
                'Category': category,
                'Title': title,
                'ItemCompatibilityList': {
                    'Compatibility': {
                        {'CompatibilityNotes': 'Fits for all trims and engines.'},
                        {'NameValueList': {'Name':'Year','Value':'2001'}},
                        {'NameValueList': {'Name':'Make','Value':'Honda'}},
                        {'NameValueList': {'Name':'Model','Value':'Accord'}}}}}}

    api = trading(domain=DomainUrl, appid=Id_App, devid=Id_Dev, certid=Id_Cert, config_file=None)
    api.execute('AddFixedPriceItem',api_request)`
            

the listing gets posted and goes active and all other information correctly gets posted, but there is no compatibility in sight. it doesnt show up at all, and i dont get any sort of error telling me what i did wrong.

one compatibility item for eBayMotors is:

    `[Honda, Accord, 2002]`

but what i want is several compatibility items:

    `[Honda, Accord, 2002], [Honda, Accord, 2003], [Honda, Accord, 2004]`

and so on. Three or four days ago, I actually got it to work as one single compatibility item at a time. But i changed my code around to accomodate having multiple years, and somewhere in the mix i ended up completely losing track of the code that worked. i have been working endlessly since i lost it, and i still cant figure out how to do it right. im not sure if the data scructure is setup incorrectly, of if theres something else that im missing. any help would be greatly appreciated.

**Comment by timotheus** [comment]
Hi - I think this is what you're looking for.

https://github.com/timotheus/ebaysdk-python/blob/master/tests/test_request.py#L20

```
motors_dict = {
            'Item': {
                'Category': '101',
                'Title': 'My Title',
                'ItemCompatibilityList': {
                    'Compatibility': [
                        {
                            'CompatibilityNotes': 'Fits for all trims and engines.',
                            'NameValueList': [
                                {'Name': 'Year', 'Value': '2001'},
                                {'Name': 'Make', 'Value': 'Honda'},
                                {'Name': 'Model', 'Value': 'Accord'}
                            ]
                        },
                    ]
                }
            }
        }
```

**Comment by soflauto** [comment]
how would you request this in reverse ?, i want to pull the compatibility based on ebay item number
