### ISSUE TITLE
How can I access the Post Order API, since the return management API is not in use anymore?

### ISSUE THREAD

**Issue by shivambats** [timotheus/ebaysdk-python#193]
It would be of great help if I can get to know how to manage the returns and cancellations of the order through the SDK.  

Thanks.

**Comment by timotheus** [comment]
This SDK support the Trading API. Which handles Orders, not sure about returns.

https://developer.ebay.com/devzone/xml/docs/reference/ebay/index.html

Sample call,
https://github.com/timotheus/ebaysdk-python/blob/master/samples/trading.py#L302

**Comment by djchou** [comment]
Here's how i was able to access my returns using the post order api.  

Populate the token variable with your token string.

```
import requests

token = #ENTER YOUR TOKEN HERE 

url = 'https://api.ebay.com/post-order/v2/return/search'
headers = {'Authorization': 'TOKEN '+token,
           'Content-Type':'application/json',
           'X-EBAY-C-MARKETPLACE-ID':'EBAY_US'}
r = requests.get(url, headers=headers)
returns = r.json()['members']
```
