### ISSUE TITLE
Understanding how to Change Global ID

### ISSUE THREAD

**Issue by ninamculver** [timotheus/ebaysdk-python#194]
Currently I am attempting to change the global ID for the finding API. 
I attempted to include it in my response like so: 
`response = api.execute('findItemsAdvanced', {'X-EBAY-SOA-GLOBAL-ID':'EBAY-ES'}, searchterms)`
But this returns that no keyword exists. (If I disclude the Global ID portion it works fine). 
If I add it to my search terms it doesn't filter to only Spain for this example, all outputs are still just eBay.com.
`searchterms = {'X-EBAY-SOA-GLOBAL-ID':'EBAY-ES',
                               'keywords': device,
                                    'categoryId' : categoryid,
                                    'itemFilter': [
                                        {'name': 'ListingType', 'value':listingtypev[l]},
                                        {'name': 'Condition', 'value': conditionv[c] },
                                        #{'name': 'HideDuplicateItems', 'value' : 'true'}, 
                                        {'name': 'MaxPrice', 'value': PriceMax},
                                        {'name': 'MinPrice', 'value': PriceMin},
                                        {'name': 'SoldItemsOnly', 'value': completedlistingsv[cl]}
                                    ],
                                    'outputSelector': ['item','SellerInfo']}`
Those are my search terms. 
They work fine in the for loop as I expected, however, I'm just struggling to get countries outside of the US. 
I've read the API documentatoin and it appears that the GLOBAL ID is one of the primary calls, pre-keyword. 
Thanks, 
Nina

**Comment by timotheus** [comment]
Putting it in the body of the request won't work, as far as I know. 

X-EBAY-SOA-GLOBAL-ID can be defined it two ways. 

1) Connection(..., siteid='EBAY-ES') constructor
2) EBAY_YAML file (https://github.com/timotheus/ebaysdk-python/wiki/YAML-Configuration)

**Comment by ninamculver** [comment]
Thank you ! 
I was attempting to find the optimal way to do it and this helps a lot.
