### ISSUE TITLE
Suddenly Returning Error after Months of Working

### ISSUE THREAD

**Issue by ninamculver** [timotheus/ebaysdk-python#210]
I've noticed for the past few days my eBay API pull has timed out and hasn't been pulling. I know for certain I have been approved to run up to a certain limit per day and have been under that this whole time. 
I have not changed the code at all, however it is returning the following error: 
`response = api.execute('findItemsAdvanced', searchterms)
Traceback (most recent call last):

  File "<ipython-input-6-065606d8fc3b>", line 1, in <module>
    response = api.execute('findItemsAdvanced', searchterms)

  File "C:\Users\this\AppData\Local\Continuum\Anaconda3\lib\site-packages\ebaysdk\connection.py", line 127, in execute
    self.error_check()

  File "C:\Users\this\AppData\Local\Continuum\Anaconda3\lib\site-packages\ebaysdk\connection.py", line 218, in error_check
    estr = self.error()

  File "C:\Users\this\AppData\Local\Continuum\Anaconda3\lib\site-packages\ebaysdk\connection.py", line 334, in error
    error_array.extend(self._get_resp_body_errors())

  File "C:\Users\this\AppData\Local\Continuum\Anaconda3\lib\site-packages\ebaysdk\finding\__init__.py", line 227, in _get_resp_body_errors
    dom = self.response.dom()`

Has anyone else encountered this? Any assistance would be of great use

edit: 
Here is an example of a search term: 
`{'categoryId': '9355',
 'itemFilter': [{'name': 'ListingType', 'value': 'FixedPrice'},
  {'name': 'Condition', 'value': ['New', '1000', '1500']},
  {'name': 'HideDuplicateItems', 'value': 'true'},
  {'name': 'MaxPrice', 'value': '649'},
  {'name': 'MinPrice', 'value': '0'},
  {'name': 'SoldItemsOnly', 'value': 'true'}],
 'keywords': 'IPHONE 6 PLUS 64GB - ATT',
 'outputSelector': ['item', 'SellerInfo'],
 'sortOrder': 'BestMatch'}`
Like I said, nothing has changed.

**Comment by timotheus** [comment]
Any chance you have the full request/response?

**Comment by ninamculver** [comment]
The API is connecting when I make the call `api = Connection(appid=ProdAppID, config_file=None, siteid=globalIDv[g])`, however when I take the next step ` response = api.execute('findItemsAdvanced', searchterms)   `, no response is returned. An example of searchterms variable can be seen above. 

Thanks,,

**Comment by ninamculver** [comment]
The API is connecting when I make the call api = Connection(appid=ProdAppID, config_file=None, siteid=globalIDv[g]), however when I take the next step response = api.execute('findItemsAdvanced', searchterms), no response is returned. An example of searchterms variable can be seen above.

Sorry. I didn't mean to close this. 

Thanks,

**Comment by timotheus** [comment]
If you enable debug (debug=True) then the raw request/response will be logged to stderr. This will help with debugging.

example, https://github.com/timotheus/ebaysdk-python/blob/master/samples/finding.py#L42

**Comment by ninamculver** [comment]
I attempted to do this, however there was still no success. 
` api = Connection(appid=ProdAppID, config_file=None, siteid=globalIDv[g], debug=True, warnings = True)
                            response = api.execute('findItemsAdvanced', searchterms)  `
With the following response: 
'AttributeError: 'Response' object has no attribute '_dom'


response
Traceback (most recent call last):

  File "<ipython-input-16-60e473933578>", line 1, in <module>
    response

NameError: name 'response' is not defined'
