### ISSUE TITLE
Error installing ebaysdk

### ISSUE THREAD

**Issue by rodriguesraphael** [timotheus/ebaysdk-python#223]
When trying to install ebaysdk does not conclude.

root@6c39e9c357bd:/# pip3 --no-cache-dir install ebaysdk
Collecting ebaysdk
Downloading ebaysdk-2.1.4.tar.gz (40kB)
100% |################################| 51kB 47kB/s
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "/tmp/pip-build-ybr869ll/ebaysdk/setup.py", line 26, in 
open(VERSIONFILE, "rt").read(), re.M).group(1)
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 29: ordinal not in range(128)

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ybr869ll/ebaysdk/

**Comment by timotheus** [comment]
Thanks. I just noticed this too. I will commit a fix asap.

**Comment by timotheus** [comment]
fixed on master and deployed version 2.1.5 to pypi
