### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by JackieBlue1970** [timotheus/ebaysdk-python#274]
People who developed the samples should be ashamed at the lack of comments.  I appreciate the hard work people put into these things.  However, it is mostly for nought if there are no comments explaining what is going on.  I will make it a point to see if I can add comments once I understand more thoroughly what is attempting to be done.

RULE 1:  THERE IS NO SUCH THING AS SELF DOCUMENTED CODE

**Comment by timotheus** [comment]
wow, why don't you try contributing to an open source project before you start throwing stones.

Constructive comments and feedback are far more productive (and appreciated) than the approach you took.

**Comment by JackieBlue1970** [comment]
Actually I thought I was civil.  I also noted once I get a better understanding, I will provide the samples.  I'm new to Python but have developed for 30 years.   I appreciate the work that is done, as I noted.   But, as is often found in open source it is either outdated or improperly documented.  From looking at past comments, I'm not the only person who has noted this issue.  Thanks for reviewing.

**Comment by timotheus** [comment]
Great! Thank you for wanting to contribute. Looking forward to see a pull request.
