### ISSUE TITLE
Finding API returning 0 results?

### ISSUE THREAD

**Issue by marlon-wiprud** [timotheus/ebaysdk-python#291]
Just getting started with this library and for some reason my call to `findItemsAdvanced` will return 0 items regardless of keywords searched. 

I am sure I am overlooking something - here is the code
```
from ebaysdk.exception import ConnectionError
from ebaysdk.finding import Connection

try:
    api = Connection(config_file='ebay.yaml', siteid="EBAY-US", https=True,
                     domain='svcs.sandbox.ebay.com')

    params = {
        'keywords': 'books',
        'paginationInput': {
            'entriesPerPage': 100
        }
    }
    response = api.execute('findItemsAdvanced', params)

    print(response.json())


except ConnectionError as e:
    print(e)
    print(e.response.dict())
```

and the response: 
```
{"ack": "Success", "version": "1.13.0", "timestamp": "2019-11-17T04:36:47.814Z", "searchResult": {"_count": "0"}, "paginationOutput": {"pageNumber": "0", "entriesPerPage": "100", "totalPages": "0", "totalEntries": "0"}, "itemSearchURL": "https://shop.sandbox.ebay.com/i.html?_nkw=books&_ddo=1&_ipg=100&_pgn=1"}
```

any pointers greatly appreciated.

**Comment by gensis20100** [comment]
I'm facing the issue. What is wrong?

**Comment by timotheus** [comment]
It appears the sandbox environment doesn't contain any listings. You might
consider switching to prod or filing it as an issue on the development site.

https://www.sandbox.ebay.com/sch/i.html?&_from=R40&_trksid=p2380057.m570.l1313.TR0.TRC0.H0.Xbook.TRS0&_nkw=book

**Comment by fsmosca** [comment]
> Just getting started with this library and for some reason my call to `findItemsAdvanced` will return 0 items regardless of keywords searched.
> 
> I am sure I am overlooking something - here is the code
> 
> ```
> from ebaysdk.exception import ConnectionError
> from ebaysdk.finding import Connection
> 
> try:
>     api = Connection(config_file='ebay.yaml', siteid="EBAY-US", https=True,
>                      domain='svcs.sandbox.ebay.com')
> 
>     params = {
>         'keywords': 'books',
>         'paginationInput': {
>             'entriesPerPage': 100
>         }
>     }
>     response = api.execute('findItemsAdvanced', params)
> 
>     print(response.json())
> 
> 
> except ConnectionError as e:
>     print(e)
>     print(e.response.dict())
> ```
> 
> and the response:
> 
> ```
> {"ack": "Success", "version": "1.13.0", "timestamp": "2019-11-17T04:36:47.814Z", "searchResult": {"_count": "0"}, "paginationOutput": {"pageNumber": "0", "entriesPerPage": "100", "totalPages": "0", "totalEntries": "0"}, "itemSearchURL": "https://shop.sandbox.ebay.com/i.html?_nkw=books&_ddo=1&_ipg=100&_pgn=1"}
> ```
> 
> any pointers greatly appreciated.

This  one is working for me now. We probably need to close this issue.
