### ISSUE TITLE
eBay Finding API moving to HTTPS only

### ISSUE THREAD

**Issue by jwolle1** [timotheus/ebaysdk-python#298]
I just wanted to check if `ebaysdk.finding()` will continue to work after the March 31, 2020 transition. Details [here](https://developer.ebay.com/news/https-only-finding-api).

Thanks for your work on this project.

**Comment by someidiot** [comment]
I've done some analysis and you can enable HTTPS in your initial connection, it's off by default:

api = Finding(appid=blah, config_file=None, https=True)

**Comment by jwolle1** [comment]
Much appreciated.
