### ISSUE TITLE
Product weight

### ISSUE THREAD

**Issue by Olimhon31** [timotheus/ebaysdk-python#304]
I am facing the problem which is the weight of the product.how can i can get product weight ? I used  trading api but most of weight of the products equal to 0.
 is there any way to get product weight all the time? I requested like this:
`response = api_trading.execute('GetItem' , {"ItemID":"184097524395",'DestinationPostalCode':'2940','DestinationCountryCode':'GB'})`

THANK YOU!!!

**Comment by fsmosca** [comment]
It seems like if the seller does not indicate a weight in the first place, the api has nothing to show for it.

If shipping is free, most likely the seller does not bother entering the weight of the item. So perhaps find those products whose shipping is not free, maybe the seller will indicate the weight for shipping calculations.

`"ShippingDetails": {"ShippingType": "Calculated"}`

I also tried GetItem and it can show weight of the item as long as weight is available. I also tried GetItemShipping and it can show weight of item if available, but needs DestinationPostalCode.
