### ISSUE TITLE
ConnectionResetError when trying to use ebaysdk.finding

### ISSUE THREAD

**Issue by MMCore** [timotheus/ebaysdk-python#305]
![image](https://user-images.githubusercontent.com/13641960/78987242-d34fd700-7b70-11ea-95a2-bdf57733b2ef.png)

When I run this program using a valid ebay api token, I get the following error printed out:
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

I have tested this code on three separate devices with different IP addresses and the exact same error is present.

**Comment by dmcherkas** [comment]
This issue accrues because finding API started to use HTTPs requests. Is there suppose changes in library or we need to find something else?

**Comment by fsmosca** [comment]
`api = ...(..., https=True, ...)`
