### ISSUE TITLE
Delivery type "Collection in person only"

### ISSUE THREAD

**Issue by Olimhon31** [timotheus/ebaysdk-python#316]
is it possible to filter out the products which is delivery type "Collection in person only" in Finding API? Thank you!!!

**Comment by fsmosca** [comment]
As I understand this is like free local pickup, the buyer will pick up the item.

You can use LocalPickupOnly and set it to true.

The result would look like this.
`"shippingType": "FreePickup",`

        "shippingInfo": {
            "shippingServiceCost": {
                "_currencyId": "USD",
                "value": "0.0"
            },
            "shippingType": "FreePickup",
            "shipToLocations": "Worldwide",
            "expeditedShipping": "true",
            "oneDayShippingAvailable": "false",
            "handlingTime": "1"
        },

I tried the call index findItemsAdvanced()

**Comment by Olimhon31** [comment]
@fsmosca  i tried as you said . `ShippingType` of most products  were `FreePickup` but some of them are different(`Flat`,`Calculated`,`Free`). Should it be like this or different?

**Comment by Olimhon31** [comment]
```
response = api.execute('findItemsAdvanced',{
'keywords': 'nike'
            'itemFilter': [
   {
                        'name':'LocalPickupOnly',
                        'value':"true"
                    }          
                ],
})
```

**Comment by fsmosca** [comment]
> @fsmosca i tried as you said . `ShippingType` of most products were `FreePickup` but some of them are different(`Flat`,`Calculated`,`Free`). Should it be like this or different?

Free - shipping is free and items will be shipped according to the buyer's specified delivery address.
FreePickUp - there is no shipping cost charged to the buyer, but the buyer will pick up the item at a place specified by the seller.
Both shippings are free but there is a difference.

**Comment by fsmosca** [comment]
> ```
> response = api.execute('findItemsAdvanced',{
> 'keywords': 'nike',
>             'itemFilter': [
>    {
>                         'name':'LocalPickupOnly',
>                         'value':"true"
>                     }          
>                 ],
> })
> ```

Yes that one.

**Comment by Olimhon31** [comment]
I think you have misunderstood me - I need to remove all the products which are "Collection in person only" from my query. How do I set LocalPickupOnly to False?

**Comment by fsmosca** [comment]
Sorry I did misinterpret what you want.

It is returning perhaps all shipping types whether LocalPickupOnly is True or False.

You better try other call index.

If it cannot filter out, just take all shipping types, and run another process to remove the FreePickup shipping type.
