### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by JackieBlue1970** [timotheus/ebaysdk-python#63]
![ebaysdkerror](https://cloud.githubusercontent.com/assets/7108463/2561901/cea28adc-b82f-11e3-90a3-69ad6c901bd8.jpg)
I'm trying to install the ebay python SDK.  I am using Python 3.3 on windows 8.1.  Unfortunately I'm too new to Python to be able to debug the issue. I run the final step python.exe setup.py.  I get an error:  File "c:\Python33\Lib\site-packages\setuptools\dist.py", line 103 except  ValueError ^, e:.   I have also attached a screenshot of the console window showing the text.  I would appreciate any help that is available. Thanks.  Jack

**Comment by timotheus** [comment]
Looking more closely at this it seems this is an error with Python 3's setuptools..
