### ISSUE TITLE
Shopping api: NameValueList doesn't necessarily return a list

### ISSUE THREAD

**Issue by matthewruttley** [timotheus/ebaysdk-python#65]
This tripped up my code. You can make a request:

    from ebaysdk.shopping import Connection
    api = Connection(appid=whatever)
    api.execute('GetSingleItem', {'ItemID': 999999999, 'IncludeSelector':'ItemSpecifics'})

Then, with the result:

    api.response_dict()['Item']['ItemSpecifics']['NameValueList']

Usually this is a list datatype so its fine, but if there is only one name/value pair it returns a single dictionary `{name:value}` rather than a dictionary as the only element of a list `[{name:value}]`

Easy to accommodate for this, I know, but if the key is called `xyzList` then it should probably always return a `list` datatype. 

This is a really hard to notice bug, since in 99.9999% of all cases, if there are any item specifics, there's more than 1 so it seems like it always returns a list, but sometimes not - which took a while to debug.

**Comment by timotheus** [comment]
https://github.com/timotheus/ebaysdk-python/wiki/Migrating-from-v1-to-v2#whats-new

This is handled in the response class. It'll force the proper datatype on a given element.

https://github.com/timotheus/ebaysdk-python/blob/master/ebaysdk/finding/__init__.py#L92
