### ISSUE TITLE
Install linux: pyconfig.h No such file or directory

### ISSUE THREAD

**Issue by greg121** [timotheus/ebaysdk-python#83]
I get this error after running sudo easy_install ebaysdk

gevent/gevent.core.c:9:22: fatal error: pyconfig.h: No such file or directory
 #include "pyconfig.h"
                      ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by fbwfbi** [comment]
Thanks~

**Comment by fenderrex** [comment]
Hey timotheus I guess the install file never got updated? Iv had to do this twice on two different builds... so i thought id give this a bump.

**Comment by AraHaan** [comment]
What version of python are the headers installed for? 3.4? 3.5? 3.6? 3.7? What if I need specifically the 3.6.0  ones?

**Comment by xibuka** [comment]
For python 3, you need to install 
    yum install python3-devel
    yum install python3-lxml

**Comment by linhu123** [comment]
E: Unable to locate package python-devel

**Comment by bryon-czoch** [comment]
sudo apt-get install python-dev

**Comment by inegmdev** [comment]
> For python 3, you need to install yum install python3-devel yum install python3-lxml

Thanks for the tip!
