### ISSUE TITLE
Retry Strategy on Request failure

### ISSUE THREAD

**Issue by kashifusmani** [timotheus/ebaysdk-python#85]
I just want to double check if ebaysdk-python contains retry strategy if the requests/service calls to EBay fails. So, for example, if the service call fails and before execute() throws ConnectionError, is the service call retried?
I did go through the source code of Connection (https://github.com/timotheus/ebaysdk-python/blob/master/ebaysdk/connection.py) and did not see any. Please clarify.

**Comment by timotheus** [comment]
I let requests handle the retries

https://github.com/timotheus/ebaysdk-python/blob/master/ebaysdk/connection.py#L63
