### ISSUE TITLE
Python2 UnicodeDecodeError when using non-ascii data along with an unicode auth token

### ISSUE THREAD

**Issue by thomasWajs** [timotheus/ebaysdk-python#91]
Issue occurs on Python2, when setting an eBayAuthToken of unicode type, then send a request with non-ascii characters (in title or description)

```python
api = Trading(token=unicode(self.user_auth.auth_token))
api.execute('AddItem', {
    "Item": {
        "Title": "é"
    }
})
```
```
  File "ebaysdk/ebaysdk/connection.py", line 118, in execute
    self.build_request(verb, data, verb_attrs)
  File "ebaysdk/ebaysdk/connection.py", line 147, in build_request
    data=self.build_request_data(verb, data, verb_attrs),
  File "ebaysdk/ebaysdk/trading/__init__.py", line 696, in build_request_data
    xml += dict2xml(data)
```

xml is casted to a unicode at line 689:
xml += "<eBayAuthToken>%s</eBayAuthToken>" % self.config.get('token')

then a string containing utf-8 encoded non-ascii data is appended to the unicode xml and fails to be decoded
xml += dict2xml(data)

**Comment by SebastianBr** [comment]
I face the same problem. Did you find a solution?

**Comment by thomasWajs** [comment]
I cast the data to byte-string instead of unicode-string before calling the sdk

**Comment by bimusiek** [comment]
We have the same issue. Funny part is that when running tests in sdk with special chars it works. So needs to be some environmental variable or project settings. 
I am trying to investigate it.

**Comment by timotheus** [comment]
Make sure you're telling python to expect unicode in the file by placing this on the first line "# -*- coding: utf-8 -*-"

**Comment by bimusiek** [comment]
Yes, we have by default

    # encoding: utf-8
    from __future__ import absolute_import, unicode_literals

I think problem is that even after encoding it with `encode('utf-8')` it is still `unicode` so it is evaluated to it and then when applied to str it fails.  I am trying to fix it within our project.

**Comment by timotheus** [comment]
Ok, great. Please let me know if/how the SDK can better handle it. I thought I had nailed down all unicode issues.

**Comment by bimusiek** [comment]
I found an issue, I will prepare MR in ~1h.
