### ISSUE TITLE
when I try to verify a product sending to eBay, I always get the following response code

### ISSUE THREAD

**Issue by temmink** [timotheus/ebaysdk-python#96]
When I try to send (verify) a product auction i always got this error message in my log file.

ebaysdk: VerifyAddItem: Class: RequestError, Severity: Error, Code: 21916892, Unknown exclude ship to location provided.The location "Invalid" provided in exclude ship to location is unknown. Please use 2-character ISO codes for countries and full names for regions/continents. See API documentation for further details.

Even when i set explicitly set a country code (for e.g. NL)

Anyone know a fix, or workaround

**Comment by timotheus** [comment]
Hi - for this, you'll get much better help from the dev forums. 

https://forums.developer.ebay.com

-Tim
