### ISSUE TITLE
Can't specify number of entries per page while using search api

### ISSUE THREAD

**Issue by Igonato** [timotheus/ebaysdk-python#97]
Hi there. Using search api I want to set  [entriesPerPage request parameter](http://developer.ebay.com/DevZone/finding/CallRef/findItemsAdvanced.html#Request.paginationInput.entriesPerPage). I'm trying to do it like so:

```
response = api.execute('findItemsAdvanced', {
     'keywords': query,
     'paginationInput.entriesPerPage': 10,
})
```
Id doesn't seem to work,  I get the default 100 per page. What am I doing wrong here?

**Comment by timotheus** [comment]
instead of using dot notation, switch it to a dictionary.

response = api.execute('findItemsAdvanced', {
     'keywords': query,
     'paginationInput': {'entriesPerPage': 10},
})

**Comment by Igonato** [comment]
@timotheus It works, thank you!
